### ISSUE TITLE
Is it complete?

### ISSUE THREAD

**Issue by himanshu-** [manjurulhoque/laravel-udemy-clone#1]
Hi, Is this clone is complete? I set it up with my localhost and found that only the home page is working.
There is not any admin part which can be used to manage courses.
Do you have a completed one?

**Comment by DanielOX** [comment]
@himanshu-  check master branch, i guess if it doesn't work then it means its not complete

**Comment by manjurulhoque** [comment]
@himanshu- @DanielOX I didn't create admin part for this project yet.
